# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221


functions:
"""
Handler endpoints, self-explanatory
"""
  create:
    handler: handler.create
    events:
      - http:
          path: events/create
          method: post

  get_active:
    handler: handler.get_active
    events:
      - http:
          path: events/active
          method: get

  get_inactive:
    handler: handler.get_inactive
    events:
      - http:
          path: events/inactive
          method: get

  get_completed:
    handler: handler.get_completed
    events:
      - http:
          path: events/completed
          method: get
  all:
    handler: handler.all
    events:
      - http:
          path: events/
          method: get

#active inactive completed, all - everything for the last 24 hrs

resources:
    Resources:
      eventsTable:
        # DynamoDB Schema and our data structure
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: events
          AttributeDefinitions:
            - AttributeName: event_id
              AttributeType: N
            - AttributeName: event_name
              AttributeType: S
            - AttributeName: status
              AttributeType: S
            - AttributeName: start_date
              AttributeType: S
            - AttributeName: end_date
              AttributeType: S

          KeySchema:
            - AttributeName: event_id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

plugins:
- serverless-python-requirements

custom:
  # Python is used in a dockerized environment when on non linux environments
  pythonRequirements:
    dockerizePip: non-linux